language: php

env:
    - NETTE=default # dev
    - NETTE=nette-2.2
    - NETTE=nette-2.1
    - NETTE=nette-2.0
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
matrix:
    allow_failures:
        - php: hhvm
before_script:
    - "php tests/prepare-composer.php"
    - composer self-update
    - composer install --no-interaction --prefer-source --dev
script: ./vendor/bin/tester -c ./tests/php.ini ./tests/WriteligentTests/
after_failure:
    - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
